app_featurename:
    resource: "@AppBundle/Resources/config/routing/featurename.yml"
    prefix:   /featurename    

app_unitmeasure:
    resource: "@AppBundle/Resources/config/routing/unitmeasure.yml"
    prefix:   /unitmeasure  

app_warehouse:
    resource: "@AppBundle/Resources/config/routing/warehouse.yml"
    prefix:   /warehouse
    
app_vatrate:
    resource: "@AppBundle/Resources/config/routing/vatrate.yml"
    prefix:   /vatrate 

app_category:
    resource: "@AppBundle/Resources/config/routing/category.yml"
    prefix:   /category 
    
yaml_route_raspuns:
    path:     /raspuns/htmlmvc
    defaults: { _controller: AppBundle:Default:raspunsHtmlMvc }
    
yaml_route_flasf:
    path:     /flash/{numar}
    defaults: { _controller: AppBundle:Default:flashMsgEx }