# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
# src/Acme/UserBundle/Resources/config/services.yml
    acme_user.registration.completed:
        class: Acme\UserBundle\EventListener\UserRegistrationListener
        arguments: [@router]
        tags:
            - { name: kernel.event_subscriber }